// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_msgid.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "proto_msgid.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::EnumDescriptor* CS_MESSAGE_ID_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* SC_MESSAGE_ID_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_proto_5fmsgid_2eproto() {
  protobuf_AddDesc_proto_5fmsgid_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "proto_msgid.proto");
  GOOGLE_CHECK(file != NULL);
  CS_MESSAGE_ID_descriptor_ = file->enum_type(0);
  SC_MESSAGE_ID_descriptor_ = file->enum_type(1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_proto_5fmsgid_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_proto_5fmsgid_2eproto() {
}

void protobuf_AddDesc_proto_5fmsgid_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  static const char descriptor[] = {  "\n\021proto_msgid.proto*;\n\rCS_MESSAGE_ID\022\024\n\020"
      "cs_message_begin\020\000\022\024\n\016cs_message_end\020\377\377\003"
      "*;\n\rSC_MESSAGE_ID\022\024\n\020sc_message_begin\020\000\022"
      "\024\n\016sc_message_end\020\377\377\003"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(    descriptor, 141);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "proto_msgid.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_proto_5fmsgid_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_proto_5fmsgid_2eproto {
  StaticDescriptorInitializer_proto_5fmsgid_2eproto() {
    protobuf_AddDesc_proto_5fmsgid_2eproto();
  }
} static_descriptor_initializer_proto_5fmsgid_2eproto_;
const ::google::protobuf::EnumDescriptor* CS_MESSAGE_ID_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CS_MESSAGE_ID_descriptor_;
}
bool CS_MESSAGE_ID_IsValid(int value) {
  switch(value) {
    case 0:
    case 65535:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* SC_MESSAGE_ID_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SC_MESSAGE_ID_descriptor_;
}
bool SC_MESSAGE_ID_IsValid(int value) {
  switch(value) {
    case 0:
    case 65535:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
