procs:
 proc_list:
  server_config:
      layer: world
      func_id: 62
      flag: notapp
      local_start: false                    #need start in local proc mgr 
      deploy_unit: group_host
  tbusd:
      layer: world
      func_id: 63
      conf_file_prefix: tbusd.xml
      deploy_unit: group_host
      local_start: false
      start_seq: 0
  tlogd:
      layer: world 
      func_id: 61
      conf_file_prefix: tlogd.xml
      deploy_unit: group_tlogd
      local_start: false
  tconnd:
      layer: world
      func_id: 1
      conf_file_prefix: tconnd.xml
      deploy_unit: group_conn
      attrs: 
          backend_server_func_id: 7
      inst_attrs:
          tconnd_port: inst+7200
  conn_server:
      layer: world
      func_id: 7
      deploy_unit: group_conn
      tlog_config:
           text:
             - local
             - tlogd
  db_proxy:
      layer: world
      func_id: 8
      deploy_unit: group_db
      tlog_config:
           text:
             - local
  game_server:
      layer: world
      func_id: 2
      deploy_unit: group_gs
      tlog_config:
          text: 
            - local
            - tlogd
          oss: 
            - local
          monlog: 
            - local
  router_server:
      layer: world
      func_id: 3
      deploy_unit: group_host
      tlog_config:
          text: 
            - local
          oss: 
            - local
          monlog: 
            - local
  service_mgr_server:
      layer: world
      func_id: 4
      deploy_unit: group_sms
      tlog_config:
          text: 
           - local
          oss: 
           - local
          monlog: 
           - local
  control_server:
      layer: world
      func_id: 5
      deploy_unit: group_control
      tlog_config:
          text: 
           - local
          oss: 
           - local
          monlog: 
           - local
  func_server:
      layer: world
      func_id: 6
      deploy_unit: group_func
      tlog_config:
          text: 
           - local
           - tlogd
          oss: 
           - local
          monlog: 
           - local
  online_server:
      layer: world
      func_id: 9
      deploy_unit: group_func
      tlog_config:
          text: 
           - local
          oss: 
           - local
          monlog: 
           - local


# if use tbus, then should describe connect relationship between procs
proc_connect:
    - peer1: router_server
      peer2: router_server
      Mask: 255.0.0.0
    - peer1: router_server
      peer2: game_server
      Mask: 255.0.0.0
      CtrlMask: local
    - peer1: tconnd
      peer2: conn_server
      Mask: 255.0.0.255
    - peer1: router_server
      peer2: conn_server
      Mask: 255.0.0.0
      CtrlMask: local
    - peer1: router_server
      peer2: db_proxy
      Mask: 255.0.0.0
      CtrlMask: local
    - peer1: router_server
      peer2: service_mgr_server
      Mask: 255.0.0.0
    - peer1: router_server
      peer2: control_server
      Mask: 255.0.0.0
      CtrlMask: local
    - peer1: router_server
      peer2: func_server
      Mask: 255.0.0.0
      CtrlMask: local
    - peer1: router_server
      peer2: online_server
      Mask: 255.0.0.0
      CtrlMask: local
